[window]
decorations = "none"
padding = { x = 10, y = 10 }
opacity = 0.5

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11.0

[colors]
[colors.primary]
background = "#000000" 
foreground = "#e6e6e6"

[colors.cursor]
text = "#0d0d0d"
cursor = "#ffcc66" 

[colors.normal]
black = "#0d0509"
red = "#E85F6F"
green = "#F29B9A"
yellow = "#D4A882"
blue = "#D9A56C"
magenta = "#D1B399"
cyan = "#E8C099"
white = "#f0eaed"

[colors.bright]
black = "#4a3c45"
red = "#FF7A8A"
green = "#FFB5B4"
yellow = "#E6BA94"
blue = "#EBB97E"
magenta = "#E3C5AB"
cyan = "#FBD2AB"
white = "#ffffff"
[colors.selection]
text = "#ffffff"
background = "#2a2a2a" 

[colors.vi_mode_cursor]
text   = "#0d0d0d"
cursor = "#66cc66" 
